// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFormulaDescription(arg1) {
  return window['go']['main']['App']['GetFormulaDescription'](arg1);
}

export function GetFormulaExpression(arg1) {
  return window['go']['main']['App']['GetFormulaExpression'](arg1);
}

export function GetFormulaName(arg1) {
  return window['go']['main']['App']['GetFormulaName'](arg1);
}

export function GetMathFormulaByIndex(arg1) {
  return window['go']['main']['App']['GetMathFormulaByIndex'](arg1);
}

export function GetMathFormulas() {
  return window['go']['main']['App']['GetMathFormulas']();
}

export function GetMathFormulasCount() {
  return window['go']['main']['App']['GetMathFormulasCount']();
}

export function GetPhysFormulaByIndex(arg1) {
  return window['go']['main']['App']['GetPhysFormulaByIndex'](arg1);
}

export function GetPhysFormulas() {
  return window['go']['main']['App']['GetPhysFormulas']();
}

export function GetPhysFormulasCount() {
  return window['go']['main']['App']['GetPhysFormulasCount']();
}

export function GetTestFuncDescription() {
  return window['go']['main']['App']['GetTestFuncDescription']();
}
