// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultMathFormula() {
  return window['go']['main']['App']['GetDefaultMathFormula']();
}

export function GetDefaultPhysFormula() {
  return window['go']['main']['App']['GetDefaultPhysFormula']();
}

export function GetFormulaDescription(arg1) {
  return window['go']['main']['App']['GetFormulaDescription'](arg1);
}

export function GetFormulaExpression(arg1) {
  return window['go']['main']['App']['GetFormulaExpression'](arg1);
}

export function GetFormulaName(arg1) {
  return window['go']['main']['App']['GetFormulaName'](arg1);
}

export function GetPhysFormulaByIndex(arg1) {
  return window['go']['main']['App']['GetPhysFormulaByIndex'](arg1);
}

export function GetTestFuncDescription() {
  return window['go']['main']['App']['GetTestFuncDescription']();
}
